---
-
# Above - sign indicates a list item. 
 
  # Target: where our play will run and options it will run with
  hosts: all
  #gather_facts: false

  # Variable: variables that will apply to the play, on all target systems
  vars: 

  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Install Winzip to remote
      win_chocolatey: 
        name: firefox
        version: 67.0.4
        state: reinstalled

  # Handlers: handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play

# Three dots indicate the end of a YAML document
#ansible-playbook firefox.yml.yml
...
